/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DashboardOrders: typeof import('./src/components/orders/DashboardOrders.vue')['default']
    DashboardProducts: typeof import('./src/components/products/DashboardProducts.vue')['default']
    DashboardUsers: typeof import('./src/components/users/DashboardUsers.vue')['default']
    DataTableOrders: typeof import('./src/components/orders/DataTableOrders.vue')['default']
    DataTableProducts: typeof import('./src/components/products/DataTableProducts.vue')['default']
    DataTableUsers: typeof import('./src/components/users/DataTableUsers.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ListProducts: typeof import('./src/components/products/ListProducts.vue')['default']
    LoginPage: typeof import('./src/components/users/LoginPage.vue')['default']
    NavBar: typeof import('./src/components/layouts/NavBar.vue')['default']
    PrincipalHome: typeof import('./src/components/PrincipalHome.vue')['default']
    ProductCard: typeof import('./src/components/products/ProductCard.vue')['default']
    ProductOrder: typeof import('./src/components/products/ProductOrder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
